---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: "simplenodeservice-team02"
  namespace: "simplenodeservice-team02-staging"
  labels:
    dt.owner: "team02"
spec:
  replicas: 1
  strategy:
    canary:
      steps:
      - setWeight: 50
      - pause: {duration: 5s}
      - setWeight: 100
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: userinterface
  template:
    metadata:
      labels:
        dt.owner: "team02"
        app.kubernetes.io/name: userinterface
        app.kubernetes.io/part-of: "simplenodeservice-team02"
        app.kubernetes.io/version: "1.0.2"
        dynatrace-release-stage: "staging"
        backstage.io/component: "default.simplenodeservice-team02-staging"
    spec:
      containers:
      - name: rollouts-demo
        image: grabnerandi/simplenodeservice:1.0.2
        env:
        - name: DT_RELEASE_VERSION
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app.kubernetes.io/version']
        - name: DT_RELEASE_PRODUCT
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app.kubernetes.io/part-of']
        - name: DT_RELEASE_STAGE
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['dynatrace-release-stage']
        - name: DT_CUSTOM_PROP
          value: "owner=team02 project=simplenodeservice stage=staging"
        - name: DT_TAGS
          value: "dt.owner=team02"
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: 3Mi
            cpu: 5m
